#pragma once

#include "CharacterSaveTypeSelectionMenu.h"
#include "CreateCharacterMenu.h"
#include "SelectCharacterMenu.h"
#include "SimulationMenu.h"
#include "ModifyHitpointManaMenu.h"
#include "IntroMenu.h"
#include "MainMenu.h"
#include "SaveLoadMenu.h"
#include "CreateSaveMenu.h"
#include "DeleteSaveMenu.h"
#include "AddSpellMenu.h"
#include "AddPotionMenu.h"
#include "ViewStatsMenu.h"
#include "EditStatsMenu.h"
